name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Replace with your default branch name
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use the Node.js version mentioned in the README

    - name: Install dependencies
      run: npm install

    - name: Build the site with Eleventy
      run: npm run build

    - name: Run Gulp to generate assets
      run: ./node_modules/gulp/bin/gulp.js

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        app_location: "src"         # The folder containing your source code
        output_location: "dist"     # The folder containing the final build output
